export const RESTUARANTS_LIST_REQUEST = 'RESTUARANTS_LIST_REQUEST';
export const RESTUARANTS_LIST_SUCCESS = 'RESTUARANTS_LIST_SUCCESS';
export const RESTUARANTS_LIST_FAIL = 'RESTUARANTS_LIST_FAIL';


